spring.application.name=mapa-RN

# Conexão com o Banco de Dados PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configurações adicionais
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2 

# Limites de tamanho para upload de arquivos (PDFs dos TCCs)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configurações do Supabase Storage
supabase.url=https://sjuvubkjelfqugeceyta.supabase.co
supabase.key=${SUPABASE_KEY}
supabase.bucket=pdfs_tcc